/**
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD open-source license, see project license.html and license.txt
 */
package edu.nps.moves.dis7.source.generator.entityTypes;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.Attributes;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

/**
 * GenerateEntityTypes creates source code from SISO enumeration definitions.
 * Created on Jul 22, 2019 by
 * MOVES Institute, Naval Postgraduate School (NPS), Monterey California USA https://www.nps.edu
 *
 * @author Don McGregor, Mike Bailey and Don Brutzman
 * @version $Id$
 */
public class GenerateEntityTypes
{
    // set defaults to allow direct run
    private        File   outputDirectory;
    private static String outputDirectoryPath = "src-generated/java/edu/nps/moves/dis7/entityTypes"; // default
    private static String         packageName =                    "edu.nps.moves.dis7.entityTypes"; // default
    private static String            language = edu.nps.moves.dis7.source.generator.GenerateOpenDis7JavaPackages.DEFAULT_LANGUAGE;
    private static String         sisoXmlFile = edu.nps.moves.dis7.source.generator.GenerateOpenDis7JavaPackages.DEFAULT_SISO_XML_FILE;
    private static String       sisoSpecificationTitleDate = "";

    private BufferedWriter uid2ClassWriter = null;

    String entitytypecommonTemplate;
    String uidfactoryTemplate;

    class TypeClassData
    {
      String pkg;
      File directory;
      StringBuilder sb;

      private String fullName;
      private String className;
      private String countryName;
      private String countryNamePretty;
      private String countryValue;
      private String entityKindName;
      private String entityKindNameDescription;
      private String entityDomainDescription; // apparently superfluous
      private String entityKindValue;
      private String entityDomainName;
      private String entityDomainValue;
    //private String domainPrettyName;
      private String entityUid;
    }
    
    private String        packageInfoPath;
    private File          packageInfoFile;
    private StringBuilder packageInfoBuilder;

  /** Constructor for GenerateEntityTypes
     * @param xmlFile sisoXmlFile
     * @param outputDir outputDirectoryPath
     * @param packageName key to package name for entity types */
  public GenerateEntityTypes(String xmlFile, String outputDir, String packageName)
  {
        if (!xmlFile.isEmpty())
             sisoXmlFile = xmlFile;
        if (!outputDir.isEmpty())
            outputDirectoryPath = outputDir;
        if (!packageName.isEmpty())
           GenerateEntityTypes.packageName = packageName;
        System.out.println (GenerateEntityTypes.class.getName());
        System.out.println ("              xmlFile=" + sisoXmlFile);
        System.out.println ("          packageName=" + GenerateEntityTypes.packageName);
        System.out.println ("  outputDirectoryPath=" + outputDirectoryPath);
        
        outputDirectory  = new File(outputDirectoryPath);
        outputDirectory.mkdirs();
//      FileUtils.cleanDirectory(outputDirectory); // do NOT clean directory, results can co-exist with other classes
        System.out.println ("actual directory path=" + outputDirectory.getAbsolutePath());
        
        packageInfoPath = outputDirectoryPath + "/" + "package-info.java";
        packageInfoFile = new File(packageInfoPath);
        
        FileWriter packageInfoFileWriter;
        try {
            packageInfoFile.createNewFile();
            packageInfoFileWriter = new FileWriter(packageInfoFile, StandardCharsets.UTF_8);
            packageInfoBuilder = new StringBuilder();
            packageInfoBuilder.append("/**\n");
            packageInfoBuilder.append(" * The <code>entities</code>  packages provide a large number of autogenerated utility classes for world entities of interest.");
            packageInfoBuilder.append("\n");
            packageInfoBuilder.append(" * <p> Online references: </p>\n");
            packageInfoBuilder.append(" * <ul>\n");
            packageInfoBuilder.append(" *      <li> GitHub <a href=\"https://github.com/open-dis/open-dis7-java\" target=\"_blank\">open-dis7-java library</a> </li> \n");
            packageInfoBuilder.append(" *      <li> NPS <a href=\"https://gitlab.nps.edu/Savage/NetworkedGraphicsMV3500/-/tree/master/examples/src/OpenDis7Examples\" target=\"MV3500\">MV3500 Networked Simulation course examples</a> </li> \n");
            packageInfoBuilder.append(" *      <li> <a href=\"https://gitlab.nps.edu/Savage/NetworkedGraphicsMV3500/-/tree/master/specifications/README.md\" target=\"README.MV3500\">IEEE and SISO specification references</a> of interest</li> \n");
            packageInfoBuilder.append(" *      <li> <a href=\"https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=46172\" target=\"SISO-REF-010\" >SISO-REF-010-2022 Reference for Enumerations for Simulation Interoperability</a> </li> \n");
            packageInfoBuilder.append(" *      <li> <a href=\"https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=47284\" target=\"SISO-REF-10.1\">SISO-REF-10.1-2019 Reference for Enumerations for Simulation, Operations Manual</a></li>\n");
            packageInfoBuilder.append(" *      <li> <a href=\"https://savage.nps.edu/open-dis7-java/javadoc\" target=\"_blank\">open-dis7 Javadoc</a>, <a href=\"https://savage.nps.edu/open-dis7-java/xml/DIS_7_2012.autogenerated.xsd\" target=\"_blank\">open-dis7 XML Schema</a>and <a href=\"https://savage.nps.edu/open-dis7-java/xml/SchemaDocumentation\" target=\"_blank\">open-dis7 XML Schema documentation</a></li> </ul>\n");
            packageInfoBuilder.append("\n");
            packageInfoBuilder.append(" * @see java.lang.Package\n");
            packageInfoBuilder.append(" * @see <a href=\"https://stackoverflow.com/questions/22095487/why-is-package-info-java-useful\">Stack Overflow: why-is-package-info-java-useful</a>\n");
            packageInfoBuilder.append(" * @see <a href=\"https://stackoverflow.com/questions/624422/how-do-i-document-packages-in-java\">Stack Overflow: how-do-i-document-packages-in-java</a>\n");
            packageInfoBuilder.append(" */\n");
            packageInfoBuilder.append("\n");
            packageInfoBuilder.append("package edu.nps.moves.dis7.entities;\n");

            packageInfoFileWriter.write(packageInfoBuilder.toString());
            packageInfoFileWriter.flush();
            packageInfoFileWriter.close();
            System.out.println("Created " + packageInfoPath);
        }
        catch (IOException ex) {
            System.out.flush(); // avoid intermingled output
            System.err.println (ex.getMessage()
               + packageInfoFile.getAbsolutePath()
            );
            ex.printStackTrace(System.err);
        }
  }

  Method methodPlatformDomainFromIntMethod;
  Method methodPlatformDomainNameMethod;
  Method methodPlatformDomainDescriptionMethod;
  
  Method countryFromIntMethod;
  Method countryNameMethod;
  Method countryDescriptionMethod;
  
  Method kindFromIntMethod;
  Method kindNameMethod;
  Method kindDescriptionMethod;

  Method munitionDomainFromIntMethod;
  Method munitionDomainNameMethod;
  Method munitionDomainDescriptionMethod;
  
  Method supplyDomainFromIntMethod;
  Method supplyDomainNameMethod;
  Method supplyDomainDescriptionMethod;

  // Don't put imports in code for this, needs to have enumerations built first; do it this way
  // Update, this might now be unnecessary with the re-structuring of the projects
  private void buildKindDomainCountryInstances()
  {
    Method[] ma;
    try {
      ma = getEnumMethods("edu.nps.moves.dis7.enumerations.PlatformDomain");
      methodPlatformDomainFromIntMethod     = ma[FORVALUE];
      methodPlatformDomainNameMethod        = ma[NAME];
      methodPlatformDomainDescriptionMethod = ma[DESCRIPTION];

      ma = getEnumMethods("edu.nps.moves.dis7.enumerations.Country");
      countryFromIntMethod     = ma[FORVALUE];
      countryNameMethod        = ma[NAME];
      countryDescriptionMethod = ma[DESCRIPTION];

      ma = getEnumMethods("edu.nps.moves.dis7.enumerations.EntityKind");
      kindFromIntMethod     = ma[FORVALUE];
      kindNameMethod        = ma[NAME];
      kindDescriptionMethod = ma[DESCRIPTION];

      ma = getEnumMethods("edu.nps.moves.dis7.enumerations.MunitionDomain");
      munitionDomainFromIntMethod     = ma[FORVALUE];
      munitionDomainNameMethod        = ma[NAME];
      munitionDomainDescriptionMethod = ma[DESCRIPTION];

      ma = getEnumMethods("edu.nps.moves.dis7.enumerations.SupplyDomain");
      supplyDomainFromIntMethod     = ma[FORVALUE];
      supplyDomainNameMethod        = ma[NAME];
      supplyDomainDescriptionMethod = ma[DESCRIPTION];
    }
    catch (Exception ex) {
      throw new RuntimeException(ex.getClass().getName() + ": " + ex.getLocalizedMessage());
    }
  }
  private static final int FORVALUE = 0;
  private static final int NAME = 1;
  private static final int DESCRIPTION = 2;

  private Method[] getEnumMethods(String className) throws Exception
  {
    Method[] ma = new Method[3];

    Class<?> cls = Class.forName(className);
    ma[FORVALUE] = cls.getDeclaredMethod("getEnumForValue", int.class);
    ma[NAME] = cls.getMethod("name", (Class[]) null);
    ma[DESCRIPTION] = cls.getDeclaredMethod("getDescription", (Class[]) null);

    return ma;
  }

  String getDescription(Method enumGetter, Method descriptionGetter, int i) throws Exception
  {
      String result = "";
      if ((enumGetter == null) || (descriptionGetter == null))
          return result;
      try 
      {
        Object enumObj = getEnum(enumGetter, i);
        result = (String) descriptionGetter.invoke(enumObj, (Object[]) null);
      }
      catch (Exception e)
      {
          System.err.println (this.getClass().getName() + ".getDescription() exception:" + e);
      }
      return result;
  }

  String getName(Method enumGetter, Method nameGetter, int i) throws Exception
  {
      if (enumGetter == null)
          return ""; // TODO fix
    Object enumObj = getEnum(enumGetter, i);
    return (String) nameGetter.invoke(enumObj, (Object[]) null);
  }

  Object getEnum(Method enumGetter, int i) throws Exception
  {
    if (enumGetter == null)
    {
        System.err.println ("NPE: getEnum (enumGetter == null, i=" + i + ")");
        return null;
    }
    return enumGetter.invoke(null, i);
  }

  private void run() throws SAXException, IOException, ParserConfigurationException
  {
    SAXParserFactory factory = SAXParserFactory.newInstance();
    factory.setValidating(false);
    factory.setNamespaceAware(true);
    factory.setXIncludeAware(true);

    loadTemplates();
    buildKindDomainCountryInstances(); // TODO questionable invocation, now working...
    
    System.out.println("Generating entities:");
    MyHandler handler = new MyHandler();
    factory.newSAXParser().parse(new File(sisoXmlFile), handler);
    
    if(uid2ClassWriter != null) 
    {
       uid2ClassWriter.flush();
       uid2ClassWriter.close();
    }
    saveUidFactory();
    System.out.println (GenerateEntityTypes.class.getName() + " complete."); // TODO  + handler.enums.size() + " enums created.");
  }

  private void loadTemplates()
  {
    try {
      entitytypecommonTemplate = loadOneTemplate("entitytypecommon.txt");
      uidfactoryTemplate       = loadOneTemplate("uidfactory.txt");
    }
    catch (Exception ex) {
      throw new RuntimeException(ex);
    }
  }

  private String loadOneTemplate(String s) throws Exception
  {
    return new String(Files.readAllBytes(Paths.get(getClass().getResource(s).toURI())), StandardCharsets.UTF_8.name());
  }
  
  private void saveUidFactory()
  {
    saveFile(outputDirectory, "EntityTypeFactory.java",uidfactoryTemplate);
  }
  
  class DescriptionElem
  {
    String description            = new String();
    String packageFromDescription = new String();
    String enumFromDescription    = new String();
    ArrayList<DescriptionElem> children = new ArrayList<>();
    String value                  = new String();
    String uid                    = new String();
  }

  class EntityElem
  {
    String kind    = new String();
    String domain  = new String();
    String country = new String();
    String uid     = new String();
    List<DescriptionElem> categories = new ArrayList<>();
  }

  class CategoryElem extends DescriptionElem
  {
    EntityElem parent;
  }

  class SubCategoryElem extends DescriptionElem
  {
    CategoryElem parent;
  }

  class SpecificElem extends DescriptionElem
  {
    SubCategoryElem parent;
  }

  class ExtraElem extends DescriptionElem
  {
    SpecificElem parent;
  }

  /** XML handler for recursively reading information and autogenerating code, namely an
     * inner class that handles the SAX parsing of the XML file. This is relatively simple, if
     * a little verbose. Basically we just create the appropriate objects as we come across the
     * XML elements in the file.
     */
  public class MyHandler extends DefaultHandler
  {
    ArrayList<EntityElem> entities = new ArrayList<>();
    EntityElem            currentEntity;
    CategoryElem          currentCategory;
    SubCategoryElem       currentSubCategory;
    SpecificElem          currentSpecific;
    ExtraElem             currentExtra;
    boolean               inCot  = false;   // we don't want categories, subcategories, etc. from this group
    boolean               inCetUid30 = false;
    int                   filesWrittenCount = 0;

    @Override
    public void startElement(String uri, String localName, String qName, Attributes attributes)
    {
      if (inCot)   // don't want anything in this group
        return;

      if (attributes.getValue("deprecated") != null)
        return;
      
      if(qName.equalsIgnoreCase("revision")) {
        if(sisoSpecificationTitleDate.isEmpty()) // only want the first/latest
           sisoSpecificationTitleDate = legalJavaDoc(attributes.getValue("title") + " (" + attributes.getValue("date") + ")");
        return;
      }
      if (qName.equalsIgnoreCase("cet")) {
        if (attributes.getValue("uid").equalsIgnoreCase("30"))
          inCetUid30 = true;
        return;
      }
      // must follow setting of flag above
      if (!inCetUid30) // only want entities in this group, uid 30
        return;
      
      switch (qName) 
      {
        case "cot":
          inCot = true; // cot element, object types
          break;

        case "entity":
          currentEntity         = new EntityElem();
          currentEntity.kind    = attributes.getValue("kind");
          currentEntity.domain  = attributes.getValue("domain");
          currentEntity.country = attributes.getValue("country");
          currentEntity.uid     = attributes.getValue("uid");
          
          if (currentCategory != null) // attribute order independent
          {
                currentCategory.parent = currentEntity;
                setUniquePackageAndEmail(currentCategory, currentEntity.categories);
                currentEntity.categories.add(currentCategory);
          }
          entities.add(currentEntity);
          break;

        case "category":
          currentCategory                  = new CategoryElem();
          currentCategory.value            = attributes.getValue("value");
          currentCategory.description      = attributes.getValue("description");
          if (currentCategory.description != null)
              currentCategory.description  = currentCategory.description.replaceAll("—","-").replaceAll("–","-").replaceAll("\"", "").replaceAll("\'", "");
          currentCategory.uid              = attributes.getValue("uid");
          
          if (currentSubCategory != null) // attribute order independent
          {
                currentSubCategory.parent  = currentCategory;
                setUniquePackageAndEmail(currentSubCategory, currentCategory.children);
                currentCategory.children.add(currentSubCategory);
          }
          if (currentEntity != null) // attribute order independent
          {
                currentCategory.parent = currentEntity;
                setUniquePackageAndEmail(currentCategory, currentEntity.categories);
                currentEntity.categories.add(currentCategory);
          }
          break;

        case "subcategory_xref":
          printUnsupportedContainedELementMessage("subcategory_xref", attributes.getValue("description"), currentCategory);
          break;

        case "subcategory_range":
          printUnsupportedContainedELementMessage("subcategory_range", attributes.getValue("description"), currentCategory);
          break;
          
        case "subcategory":
          currentSubCategory                  = new SubCategoryElem();
          currentSubCategory.value            = attributes.getValue("value");
          currentSubCategory.description      = attributes.getValue("description");
          if (currentSubCategory.description != null)
              currentSubCategory.description  = currentSubCategory.description.replaceAll("—","-").replaceAll("–","-").replaceAll("\"", "").replaceAll("\'", "");
          currentSubCategory.uid              = attributes.getValue("uid");
          
          if (currentCategory != null) // attribute order independent
          {
                currentSubCategory.parent = currentCategory;
                setUniquePackageAndEmail(currentSubCategory, currentCategory.children);
                currentCategory.children.add(currentSubCategory);
          }
          break;

        case "specific_range":
          printUnsupportedContainedELementMessage("specific_range", attributes.getValue("description"), currentSubCategory);
          break;

        case "specific":
          currentSpecific                  = new SpecificElem();
          currentSpecific.value            = attributes.getValue("value");
          currentSpecific.description      = attributes.getValue("description");
          if (currentSpecific.description != null)
              currentSpecific.description  = currentSpecific.description.replaceAll("—","-").replaceAll("–","-").replaceAll("\"", "").replaceAll("\'", "");
          currentSpecific.uid              = attributes.getValue("uid");
          currentSpecific.parent           = currentSubCategory;
          
          if ((currentSubCategory != null) && (currentSubCategory.children != null))
          {
              currentSubCategory.children.add(currentSpecific);
              setUniquePackageAndEmail(currentSpecific, currentSubCategory.children);
          }
          else if (currentExtra != null) // attribute order independent
          {
                currentExtra.parent = currentSpecific;
                setUniquePackageAndEmail(currentExtra, currentSpecific.children);
                currentSpecific.children.add(currentExtra);
          }
          break;

        case "extra":
          currentExtra                  = new ExtraElem();
          currentExtra.value            = attributes.getValue("value");
          currentExtra.description      = attributes.getValue("description");
          if (currentExtra.description != null)
              currentExtra.description  = currentExtra.description.replaceAll("—","-").replaceAll("–","-").replaceAll("\"", "").replaceAll("\'", "");
          currentExtra.uid              = attributes.getValue("uid");
          
          if (currentSpecific != null) // attribute order independent
          {
                currentExtra.parent = currentSpecific;
                setUniquePackageAndEmail(currentExtra, currentSpecific.children);
                currentSpecific.children.add(currentExtra);
          }
          break;

        default:
      }
    }

    @Override
    public void endElement(String uri, String localName, String qName)
    {
      if (qName == null)
        return;
      if (!qName.equals("cot") && inCot)
        return;

      try {
        switch (qName) {
          case "cot":
            inCot = false;
            break;

          case "cet":
            if (inCetUid30)
              inCetUid30 = false;
            break;

          case "entity":
            currentEntity = null;
            break;

          case "category":
            if (currentCategory != null) //might have been deprecated
                writeCategoryFile(null);
            currentCategory = null; // reset for next time
            break;

          case "subcategory":
            if (currentSubCategory != null) // might have been deprecated
                writeSubCategoryFile(null); // Datapkt
            currentSubCategory = null; // reset for next time
            break;

          case "specific":
            if (currentSpecific != null) // might have been deprecated
              writeSpecificFile(null);
            currentSpecific = null; // reset for next time
            break;

          case "extra":
            if (currentExtra != null) // might have been deprecated
                writeExtraFile(null);
            currentExtra = null; // reset for next time
            break;

          case "subcategory_xref":
          case "subcategory_range":
          case "specific_range":
              // not supported
            break;

          default:
            break;
        }
      }
      catch (Exception ex) {
        System.err.println("endElement qName=" + qName + ", " + ex.getMessage());
        throw new RuntimeException(ex);
      }
    }

    @Override
    public void endDocument() throws SAXException
    {
    }
    
    private void addToPropertiesFile(String pkg, String className, String uid)
    {
      try {
        if(uid2ClassWriter == null)
          buildUid2ClassWriter();
        uid2ClassWriter.write(uid+"="+pkg+"."+className);
        uid2ClassWriter.newLine();
      }
      catch(IOException ex) {
        throw new RuntimeException (ex);
      }
    }
    
    private void buildUid2ClassWriter() throws IOException
    {
      File f = new File(outputDirectory,"uid2EntityClass.properties");
      f.createNewFile();
      uid2ClassWriter = new BufferedWriter(new FileWriter(f));
    }
    
    private void saveEntityFile(TypeClassData data, String uid)
    {
        data.sb.append("    }\n");
        data.sb.append("    /** Create a new instance of this final (unmodifiable) class\n");
        data.sb.append("      * @return copy of class for use as data */\n");
        data.sb.append("    public static " + data.className + " createInstance()\n");
        data.sb.append("    {\n");
        data.sb.append("            return new " + data.className + "();\n");
        data.sb.append("    }\n");
        data.sb.append("}\n");
        saveFile(data.directory, data.className + ".java", data.sb.toString());
        addToPropertiesFile(data.pkg, data.className, uid);
        
        packageInfoPath = data.directory + "/" + "package-info.java";
        File   packageInfoFile = new File(packageInfoPath);
      
        if (!packageInfoFile.exists()) // write package-info.java during first time through
        {
            FileWriter packageInfoFileWriter;
            try {
                packageInfoFile.createNewFile();
                packageInfoFileWriter = new FileWriter(packageInfoFile, StandardCharsets.UTF_8);
                packageInfoBuilder = new StringBuilder();
                packageInfoBuilder.append("/**\n");
                if (!data.countryValue.isEmpty())
                    packageInfoBuilder.append(" ").append(data.countryNamePretty);
                if (!data.entityKindName.isEmpty())
                    packageInfoBuilder.append(" ").append(data.entityKindName);
                if (!data.entityDomainName.isEmpty())
                    packageInfoBuilder.append(" ").append(data.entityDomainValue);
                if (!data.countryValue.isEmpty() && !data.entityKindName.isEmpty() && !data.entityDomainValue.isEmpty())
                    packageInfoBuilder.append(" t");
                else
                    packageInfoBuilder.append(" T");
                packageInfoBuilder.append("yped classes for world entities defined by ").append(sisoSpecificationTitleDate).append(" enumerations.\n");
                packageInfoBuilder.append("\n");
                packageInfoBuilder.append(" * <p> Online references: </p>\n");
                packageInfoBuilder.append(" * <ul>\n");
                packageInfoBuilder.append(" *      <li> GitHub <a href=\"https://github.com/open-dis/open-dis7-java\" target=\"_blank\">open-dis7-java library</a> </li> \n");
                packageInfoBuilder.append(" *      <li> NPS <a href=\"https://gitlab.nps.edu/Savage/NetworkedGraphicsMV3500/-/tree/master/examples/src/OpenDis7Examples\" target=\"MV3500\">MV3500 Networked Simulation course examples</a> </li> \n");
                packageInfoBuilder.append(" *      <li> <a href=\"https://gitlab.nps.edu/Savage/NetworkedGraphicsMV3500/-/tree/master/specifications/README.md\" target=\"README.MV3500\">IEEE and SISO specification references</a> of interest</li> \n");
                packageInfoBuilder.append(" *      <li> <a href=\"https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=46172\" target=\"SISO-REF-010\" >SISO-REF-010-2022 Reference for Enumerations for Simulation Interoperability</a> </li> \n");
                packageInfoBuilder.append(" *      <li> <a href=\"https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=47284\" target=\"SISO-REF-10.1\">SISO-REF-10.1-2019 Reference for Enumerations for Simulation, Operations Manual</a></li>\n");
                packageInfoBuilder.append(" *      <li> <a href=\"https://savage.nps.edu/open-dis7-java/javadoc\" target=\"_blank\">open-dis7 Javadoc</a>, <a href=\"https://savage.nps.edu/open-dis7-java/xml/DIS_7_2012.autogenerated.xsd\" target=\"_blank\">open-dis7 XML Schema</a>and <a href=\"https://savage.nps.edu/open-dis7-java/xml/SchemaDocumentation\" target=\"_blank\">open-dis7 XML Schema documentation</a></li> </ul>\n");
                packageInfoBuilder.append("\n");
                packageInfoBuilder.append(" * @see java.lang.Package\n");
                packageInfoBuilder.append(" * @see <a href=\"https://stackoverflow.com/questions/22095487/why-is-package-info-java-useful\">Stack Overflow: why-is-package-info-java-useful</a>\n");
                packageInfoBuilder.append(" * @see <a href=\"https://stackoverflow.com/questions/624422/how-do-i-document-packages-in-java\">Stack Overflow: how-do-i-document-packages-in-java</a>\n");
                packageInfoBuilder.append(" */\n");
                packageInfoBuilder.append("// created by edu/nps/moves/dis7/source/generator/entitytypes/GenerateEntityTypes.java\n");
                packageInfoBuilder.append("\n");
                packageInfoBuilder.append("package ").append(data.pkg).append(";\n");

                packageInfoFileWriter.write(packageInfoBuilder.toString());
                packageInfoFileWriter.flush();
                packageInfoFileWriter.close();
                System.out.println("Created " + packageInfoPath);
            }
            catch (IOException ex) {
                System.out.flush(); // avoid intermingled output
                System.err.println (ex.getMessage()
                   + packageInfoFile.getAbsolutePath()
                );
                ex.printStackTrace(System.err);
            }
        }
    }
  
    private void appendCommonStatements(TypeClassData data)
    {
      String currentSpecificName  = new String(); // handle potential nulls
      String currentSpecificValue = new String();
      if (currentSpecific != null)
      {
          currentSpecificName  = fixName(currentSpecific.description);
          currentSpecificValue = " = " + "<code>" + currentSpecific.value + "</code>";
      }
      else
      {
          currentSpecificValue  = "<code>(none)</code>"; // second of two entries to avoid whitespace
      }
      String currentSubCategoryName  = new String(); // handle potential nulls
      String currentSubCategoryValue = new String();
      if (currentSubCategory != null)
      {
          currentSubCategoryName  = fixName(currentSubCategory.description);
          // TODO often subcategories are replicated across different packages
          currentSubCategoryName  = currentSubCategoryName.substring(0,1) + 
                                    currentSubCategoryName.substring(1).replace("_","");
          currentSubCategoryValue = " = " + "<code>" + currentSubCategory.value + "</code>";
      }
      else
      {
          currentSubCategoryValue  = "<code>(none)</code>"; // second of two entries to avoid whitespace
      }
      String seeCurrentCategory = new String();
      if (!currentCategory.packageFromDescription.isEmpty())
          seeCurrentCategory = " * @see Category\n" + " * @see " + currentCategory.packageFromDescription;
      String seeCurrentSubcategory = new String();
      if (!currentSubCategoryName.isEmpty())
          seeCurrentSubcategory = " * @see SubCategory\n";
          // TODO often package-specific since repeated, sometimes numeric:  + " * @see " + currentSubCategoryName;
      
      String contents = String.format(entitytypecommonTemplate,       data.pkg,     // Class definition 
                                      data.className,                                     // Opening sentence
                                      data.className,                 data.className, // Usage 
                                      data.countryNamePretty,         data.countryValue,
                                      data.entityDomainName,          data.entityDomainValue,
                                      data.entityKindNameDescription, data.entityKindValue,
                                      currentCategory.description,    currentCategory.value,
                                      currentSubCategoryName,         currentSubCategoryValue,
                                      currentSpecificName,            currentSpecificValue,
                                      data.entityUid,
                                      sisoSpecificationTitleDate,    
                                      data.fullName,                                      // Full name
                                      data.countryName,                                   // @see Country#*
                                      data.entityKindName,                                // @see EntityKind#*
                                      data.entityDomainName,                              // @see %s (interface Domain)
                                      seeCurrentCategory,                                 // @see Category (if present)
                                      seeCurrentSubcategory,                              // @see SubCategory (if present)
                                      data.className, data.className,                 // class definition
                                      data.countryName, 
                                      data.entityKindName, 
                                      data.entityDomainName, 
                                      data.entityDomainValue);
      data.sb.append(contents);
    }

    private void appendStatement(DescriptionElem elem, String typ, StringBuilder sb)
    {
      String template = "        set"+typ+"((byte)%s); // uid %s, %s\n";
      if (elem             == null)
          return;
      if (elem.value       == null)
          elem.value        = "";
      if (elem.uid         == null)
          elem.uid          = "";
      if (elem.description == null)
          elem.description  = "";
      sb.append(String.format(template, elem.value, elem.uid, elem.description));
    }
    
    private void writeCategoryFile(TypeClassData d)
    {
      TypeClassData data = d;
      if (data == null) {
        data = buildEntityCommon(currentCategory.toString(), fixName(currentCategory),currentCategory.uid);
      }
      appendStatement(currentCategory, "Category", data.sb);

      if (d == null) {
        saveEntityFile(data,currentCategory.uid);
      }
    }

    private void writeSubCategoryFile(TypeClassData d)
    {
      if ((currentCategory == null) || (currentSubCategory == null))
      {
          System.err.println (this.getClass().getName() + " writeSubCategoryFile has problem with currentCategory or currentSubCategory null, no file written");
          if (d != null)
              System.err.println ("DataPacket d=" + d.sb.toString());
      }
          
      TypeClassData data = d;
      if (data == null) {
        data = buildEntityCommon(currentSubCategory.toString(), fixName(currentSubCategory), currentSubCategory.uid);
      }
      appendStatement(currentCategory,    "Category",    data.sb);
      appendStatement(currentSubCategory, "SubCategory", data.sb);

      if (d == null)
        saveEntityFile(data,currentSubCategory.uid);
    }

    private void writeSpecificFile(TypeClassData d)
    {
      TypeClassData data = d;
      if (data == null) {
        data = buildEntityCommon(currentSpecific.toString(), fixName(currentSpecific),currentSpecific.uid);
      }
      appendStatement(currentCategory,    "Category",    data.sb);
      appendStatement(currentSubCategory, "SubCategory", data.sb);
      appendStatement(currentSpecific,    "Specific",    data.sb);

      if (d == null)
        saveEntityFile(data,currentSpecific.uid);
    }

    private void writeExtraFile(TypeClassData d)
    {
      TypeClassData data = d;
      if (data == null) {
        data = buildEntityCommon(currentExtra.toString(), fixName(currentExtra),currentExtra.uid);
      }
      appendStatement(currentCategory,    "Category",    data.sb);
      appendStatement(currentSubCategory, "SubCategory", data.sb);
      appendStatement(currentSpecific,    "Specific",    data.sb);
      appendStatement(currentExtra,       "Extra",       data.sb);

      if (d == null)
        saveEntityFile(data,currentExtra.uid);
    }

    private TypeClassData buildEntityCommon(String fullName, String fixedName, String uid)
    {
        try {
        TypeClassData dataPacket = new TypeClassData();

        if  (fullName == null)
             dataPacket.fullName = "";
        else dataPacket.fullName = fullName;
        dataPacket.sb = new StringBuilder();
//        System.err.println("buildEntityCommon fixedName=" + fixedName + ", uid=" + uid + ", outputDirectory=" + outputDirectory); // debug trace
        
        buildPackagePath(currentEntity, dataPacket);
        dataPacket.directory = new File(outputDirectory, dataPacket.sb.toString());
        dataPacket.directory.mkdirs(); // ensure that directory exists

        // Protect against duplicate class names
        int i=1;
        while(new File(dataPacket.directory,fixedName+".java").exists()){
          fixedName = fixedName+ i++;
        }
//        System.err.println("fixedName.java=" + fixedName + ".java"); // debug trace

        String packagePath = packageName + "." + pathToPackage(dataPacket.sb.toString());
        int    countryInteger  = Integer.parseInt(currentEntity.country);
        String countryName     = getName(countryFromIntMethod, countryNameMethod, countryInteger);

        int entityDomainInteger = Integer.parseInt(currentEntity.domain);
        int entityKindInteger   = Integer.parseInt(currentEntity.kind);

        String entityKindName        = getName(kindFromIntMethod, kindNameMethod, entityKindInteger);
        String entityKindDescription = legalJavaDoc(getDescription(kindFromIntMethod, kindDescriptionMethod, entityKindInteger));
        
        String entityDomainName;
        String entityDomainDescription;
        String entityDomainValue;
        switch (entityKindName) {
          case "MUNITION":
            entityDomainName = "MunitionDomain";
            entityDomainDescription = "Munition Domain";
            entityDomainValue = getName(munitionDomainFromIntMethod, munitionDomainNameMethod, entityDomainInteger);
            break;
          case "SUPPLY":
            entityDomainName = "SupplyDomain";
            entityDomainDescription = "Supply Domain";
            entityDomainValue = getName(supplyDomainFromIntMethod, supplyDomainNameMethod, entityDomainInteger);
            break;
          case "OTHER":
          case "PLATFORM":
          case "LIFE_FORM":
          case "ENVIRONMENTAL":
          case "CULTURAL_FEATURE":
          case "RADIO":
          case "EXPENDABLE":
          case "SENSOR_EMITTER":
          default:
            entityDomainName = "PlatformDomain";
            entityDomainDescription = "Platform Domain";
            entityDomainValue = getName(methodPlatformDomainFromIntMethod, methodPlatformDomainNameMethod, entityDomainInteger);
            break;
        }

        dataPacket.pkg = packagePath;
        dataPacket.entityUid = uid; //currentEntity.uid;
        dataPacket.countryName       = countryName;
        dataPacket.countryValue      = String.valueOf(countryInteger);
        dataPacket.entityKindName    = entityKindName;
        dataPacket.entityKindValue   = String.valueOf(entityKindInteger);
        dataPacket.entityKindNameDescription = entityKindDescription;
        dataPacket.entityDomainDescription   = entityDomainDescription; // unused, apparently superfluoua
        dataPacket.entityDomainName  = entityDomainName;
        dataPacket.entityDomainValue = String.valueOf(entityDomainInteger);
        //data.domainPrettyName = domainDescription;
        dataPacket.entityDomainValue = entityDomainValue;
        dataPacket.className = fixedName;

        dataPacket.sb.setLength(0);

        appendCommonStatements(dataPacket);
        return dataPacket;
      }
      catch (Exception ex) {
        throw new RuntimeException(ex);
      }
    }
  }

  private void saveFile(File parentDir, String name, String contents)
  {
    // save file
    File target = new File(parentDir, name);
    try {
      target.createNewFile();
      try (FileWriter fw = new FileWriter(target, StandardCharsets.UTF_8)) {
        fw.write(contents);
        fw.flush();
      }
    }
    catch (IOException ex) {
      throw new RuntimeException("Error saving " + name + ": " + ex.getLocalizedMessage(), ex);
    }
  }

  private void setUniquePackageAndEmail(DescriptionElem descriptionElement, List<DescriptionElem> descriptionElementList)
  {
      if ((descriptionElement == null) || (descriptionElementList == null))
      {
          if (descriptionElement == null)
              System.err.println(this.getClass().getName() + ".setUniquePackageAndEmail() error: descriptionElement=null");
          if (descriptionElementList == null)
              System.err.println(this.getClass().getName() + ".setUniquePackageAndEmail() error: descriptionElementList=null");
          return;
      }
    String mangledDescription = fixName(descriptionElement);
    mangledDescription = makeUnique(mangledDescription, descriptionElementList);
    descriptionElement.packageFromDescription  = mangledDescription;
    descriptionElement.enumFromDescription = mangledDescription.toUpperCase();
  }

  private String makeUnique(String s, List<DescriptionElem> lis)
  {
    String news = s;
    for (int i = 1; i < 1000; i++) {
      outer:
      {
        for (DescriptionElem hd : lis) {
          if ((hd.packageFromDescription != null) && hd.packageFromDescription.equalsIgnoreCase(news))
            break outer;
        }
        return news;
      }
      news = s + i;
    }
    throw new RuntimeException("Problem generating unique name for " + s);
  }

  Pattern regex = Pattern.compile("\\((.*?)\\)");

  private String buildCountryPackagePart(String s)
  {
    if ((s == null) || s.isEmpty())
        return "";
    Matcher m = regex.matcher(s);
    String fnd = null;
    while (m.find()) {
      fnd = m.group(1);
      if (fnd.length() == 3)
        break;
      fnd = null;
    }
    if (fnd != null)
      return fnd.toLowerCase();

    s = fixName(s);
    s = s.toLowerCase();
    if (s.length() > 3)
      return s.substring(0, 3);
    else
      return s;
  }

/**
 * Naming conventions for cleaning up provided names
 * @param s enumeration string from XML data file
 * @return normalized name
 */
  private String buidKindOrDomainPackagePart(String s)
  {
    s = fixName(s);
    s = s.replaceAll("_", "");
    s = s.toLowerCase();
    return s;
  }
  
  //Country, kind, domain 
  private void buildPackagePath(EntityElem ent, TypeClassData data) throws Exception
  {
    if (data == null)
        System.err.println("buildPackagePath data.sb 0: data = null");
    if (data.sb == null)
        System.err.println("buildPackagePath data.sb 0.5: data.sb = null");
//    if  (data.sb.toString().isEmpty())
//         System.err.println("buildPackagePath data.sb 1: empty string");
//    else System.err.println("buildPackagePath data.sb 1: " + data.sb.toString());
    
    String countryDescription = GenerateEntityTypes.this.getDescription(countryFromIntMethod, countryDescriptionMethod, Integer.parseInt(ent.country));
    if (countryDescription.isEmpty())
    {
        System.err.println(this.getClass().getName() + ".buildPackagePath() failure, no country description");
        return;
    }
//    System.err.println("countryDescription=" + countryDescription);
    data.countryNamePretty = countryDescription;
    data.sb.append(buildCountryPackagePart(countryDescription));
    data.sb.append("/");
//    System.err.println("buildPackagePathdata.sb 2: " + data.sb.toString());

    String kindname = getName(kindFromIntMethod, kindNameMethod, Integer.parseInt(ent.kind));
    kindname = buidKindOrDomainPackagePart(kindname);
    data.sb.append(buidKindOrDomainPackagePart(kindname));
    data.sb.append("/");
//    System.err.println("buildPackagePathdata.sb 3: " + data.sb.toString());

    String domainname;
    String kindnamelc = kindname.toLowerCase();

    switch (kindnamelc) {
      case "munition":
        domainname = getName(munitionDomainFromIntMethod, munitionDomainNameMethod, Integer.parseInt(ent.domain));
        break;
      case "supply":
        domainname = getName(supplyDomainFromIntMethod, supplyDomainNameMethod, Integer.parseInt(ent.domain));
        break;
      default:
        domainname = getName(methodPlatformDomainFromIntMethod, methodPlatformDomainNameMethod, Integer.parseInt(ent.domain));
        break;
    }

    domainname = buidKindOrDomainPackagePart(domainname);
    data.sb.append(buidKindOrDomainPackagePart(domainname));
    data.sb.append("/");
//    System.err.println("buildPackagePathdata.sb 4: " + data.sb.toString());
  }

  private String pathToPackage(String s)
  {
    s = s.replaceAll("_",""); // no underscore divider
    s = s.replace("/", ".");
    if (s.endsWith("."))
        s = s.substring(0, s.length() - 1);
    return s;
  }
/*
  private String parentPackage(String s)
  {
    return s.substring(0, s.lastIndexOf('.'));
  }
*/
  String maybeSpecialCase(String s, String dflt)
  {
    String lc = s.toLowerCase();
    if (lc.equals("united states"))
      return "USA";
    if (lc.equals("not_used"))
      return "";
    return dflt;
  }

  String smallCountryName(String s, String integ)
  {
    if (integ.equals("0"))
      return "";  // "other

    if (s.length() <= 3)
      return s;
    try {
      s = s.substring(s.indexOf("(") + 1, s.indexOf(")"));
      if (s.length() > 3) {
        return maybeSpecialCase(s, integ);
      }
      return s;
    }
    catch (Exception ex) {
      return integ;
    }
  }

  private void printUnsupportedContainedELementMessage(String elname, String eldesc, CategoryElem cat)
  {
    StringBuilder bldr = new StringBuilder();
    bldr.append(cat.description);
    bldr.append("/");
    bldr.append(cat.parent.kind);
    bldr.append("/");
    bldr.append(cat.parent.domain);
    bldr.append("/");
    bldr.append(cat.parent.country);

    System.err.println("contained XML element " + elname + " (" + eldesc + " in " + bldr.toString() + ") not supported");
  }

  private void printUnsupportedContainedELementMessage(String elname, String eldesc, SubCategoryElem sub)
  {
    StringBuilder bldr = new StringBuilder();
    bldr.append(sub.description);
    bldr.append("/");
    bldr.append(sub.parent.description);
    bldr.append("/");
    bldr.append(sub.parent.parent.kind);
    bldr.append("/");
    bldr.append(sub.parent.parent.domain);
    bldr.append("/");
    bldr.append(sub.parent.parent.country);

    System.err.println("contained XML element " + elname + " (" + eldesc + " in " + bldr.toString() + ") not supported");
  }

  private String legalJavaDoc(String s)
  {
    s = s.replace("<", "&lt;");
    s = s.replace(">", "&gt;");
    s = s.replace("&", "&amp;");
    return s;
  }
  
  private String tryParent(DescriptionElem elem)
  {
    if(elem instanceof ExtraElem )
      return fixName(((ExtraElem)elem).parent.description);

   if(elem instanceof SpecificElem )
      return fixName(((SpecificElem)elem).parent.description);

   if(elem instanceof SubCategoryElem )
      return fixName(((SubCategoryElem)elem).parent.description);

   if(elem instanceof CategoryElem )
      return "uid"+((CategoryElem)elem).parent.uid;

   return null;
  }
  
  private String makeNonNumeric(DescriptionElem elem, String s)
  {
    if(s.startsWith("_"))
      s = s.substring(1);
    
    while(isNumeric(s)) {
      String p = tryParent(elem);
      if(p == null)
        return "_"+s;
      s = p+"_"+s;
    }
    return s;
  }
  
  private boolean isNumeric(String s)
  {
    try {
      int i = Integer.parseInt(s);
      return true;
    }
    catch(NumberFormatException t) {
      return false;
    }
  }
  
  private String fixName(DescriptionElem elem)
  {
    String r = new String();
    if ((elem != null) && (elem.description != null))
    {
        r = fixName(elem.description);
        if (r.isEmpty())
            return r;
        if(!r.isEmpty() && (isNumeric(r) | isNumeric(r.substring(1))))
        {
          r = makeNonNumeric(elem,r);    
        }
        r = r.substring(0,1) + r.substring(1).replaceAll("_",""); // no underscore divider after first character
    }
    return r;
  }
  
  private String fixName(String s)
  {
    String r = s.trim();
    
    if (r.isEmpty())
        return r;
  
    // Convert any of these chars to underbar (u2013 is a hyphen observed in source XML):
    r = r.trim().replaceAll(",", " ").replaceAll("—"," ").replaceAll("-", " ").replaceAll("\\."," ").replaceAll("&"," ")
                                     .replaceAll("/"," ").replaceAll("\"", " ").replaceAll("\'", " ").replaceAll("( )+"," ").replaceAll(" ", "_");
    r = r.substring(0,1) + r.substring(1).replaceAll("_",""); // no underscore divider after first character

    r = r.replaceAll("[\\h-/,\";:\\u2013]", "_");

    // Remove any of these chars (u2019 is an apostrophe observed in source XML):
    r = r.replaceAll("[\\[\\]()}{}'.#&\\u2019]", "");

    // Special case the plus character:
    r = r.replace("+", "PLUS");

    // Collapse all contiguous underbars:
    r = r.replaceAll("_{2,}", "_");

    r = r.replaceAll("<=", "LTE");
    r = r.replaceAll("<",  "LT");
    r = r.replaceAll(">=", "GTE");
    r = r.replaceAll(">",  "GT");
    r = r.replaceAll("=",  "EQ");
    r = r.replaceAll("%",  "pct");
    
    // Java identifier can't start with digit
    if (Character.isDigit(r.charAt(0)))
        r = "_" + r;
    
    if (r.contains("__"))
    {
        System.err.println("fixname contains multiple underscores: " + r);
        r = r.replaceAll("__", "_");
    }
    // If there's nothing there, put in something:
    if (r.trim().isEmpty() || r.equals("_"))
    {
      System.err.print("fixname: erroneous name \"" + s + "\"");
      r = "undefinedName";
      if (!s.equals(r))
           System.err.print( " converted to \"" + r + "\"");
      System.err.println();
    }
    //System.out.println("In: "+s+" out: "+r);
    return r;
  }

  /** GenerateEntityTypes invocation, passing run-time arguments (if any)
     * @param args three configuration arguments, if defaults not used
     */
  public static void main(String[] args)
  {
    try 
    {
        if  (args.length == 0)
             new GenerateEntityTypes("",      "",      ""     ).run(); // use defaults
        else 
        {
            System.out.println ("GenerateEntityTypes(" + args[0] + ", " + args[1] + ", " + args[2] + ").run()");
            new GenerateEntityTypes(args[0], args[1], args[2]).run();
        }
    }
    catch (SAXException | IOException | ParserConfigurationException ex)
    {
        System.err.println(ex.getClass().getSimpleName() + ": " + ex.getLocalizedMessage());
    }
  }
}
