/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD open-source license, see project license.html and license.txt
 */
package edu.nps.moves.dis7.source.generator.entityTypes;

import edu.nps.moves.dis7.source.generator.enumerations.GenerateEnumerations;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.Attributes;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

/**
 * PythonEntityTypeGenerator creates Python entity type source code
 * from SISO enumeration definitions. Each entity type becomes a Python
 * class extending EntityType with its fields set in __init__.
 * Parallels GenerateEntityTypes.java but produces Python output.
 *
 * @see GenerateEntityTypes
 * @author DMcG (autogenerated pattern)
 */
public class PythonEntityTypeGenerator
{
    private File outputDirectory;
    private static String outputDirectoryPath = "src-generated/python/opendis7/entities";
    private static String sisoXmlFile = "xml/SISO/SISO-REF-010.xml";
    private static String sisoSpecificationTitleDate = "";

    private int entityClassCount = 0;
    private List<String> generatedClassNames = new ArrayList<>();

    /**
     * Constructor
     * @param xmlFile input SISO XML file
     * @param outputDir output directory path
     */
    public PythonEntityTypeGenerator(String xmlFile, String outputDir)
    {
        System.out.println(PythonEntityTypeGenerator.class.getName());
        if (!xmlFile.isEmpty())
            sisoXmlFile = xmlFile;
        if (!outputDir.isEmpty())
            outputDirectoryPath = outputDir;
        System.out.println("          xmlFile=" + sisoXmlFile);
        System.out.println("  outputDirectory=" + outputDirectoryPath);

        outputDirectory = new File(outputDirectoryPath);
        outputDirectory.mkdirs();
        System.out.println("actual directory path=" + outputDirectory.getAbsolutePath());
    }

    /**
     * Main entry point
     * @param args xmlFile, outputDir
     */
    public static void main(String[] args)
    {
        if (args.length >= 2)
        {
            sisoXmlFile = args[0];
            outputDirectoryPath = args[1];
        }
        PythonEntityTypeGenerator generator = new PythonEntityTypeGenerator(sisoXmlFile, outputDirectoryPath);
        try
        {
            generator.run();
        }
        catch (Exception e)
        {
            System.err.println("Error generating Python entity types: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }

    private void run() throws SAXException, IOException, ParserConfigurationException
    {
        File xmlFile = new File(sisoXmlFile);
        SAXParserFactory factory = SAXParserFactory.newInstance();
        factory.setValidating(false);
        factory.setNamespaceAware(true);
        factory.setXIncludeAware(true);

        System.out.println("Begin Python entity type generation...");
        MyHandler handler = new MyHandler();
        factory.newSAXParser().parse(xmlFile, handler);

        writeInitPy();

        System.out.println(PythonEntityTypeGenerator.class.getName() + " complete, " +
            entityClassCount + " Python entity type classes created.");
    }

    private void writeInitPy() throws IOException
    {
        File initFile = new File(outputDirectory, "__init__.py");
        initFile.createNewFile();
        FileWriter fw = new FileWriter(initFile, StandardCharsets.UTF_8);
        fw.write("#\n");
        fw.write("# Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS).\n");
        fw.write("# All rights reserved.\n");
        fw.write("# Auto-generated __init__.py for opendis7.entities package\n");
        fw.write("#\n\n");
        fw.write("# Entity type classes are organized in subdirectories.\n");
        fw.write("# Import specific entity types as needed, e.g.:\n");
        fw.write("# from opendis7.entities.usa.platform.land.M1A2Abrams import M1A2Abrams\n");
        fw.write("\n");
        fw.flush();
        fw.close();
    }

    // ========== SAX Handler ==========

    public class MyHandler extends DefaultHandler
    {
        // Current context during parsing
        private String currentCountryName = "";
        private String currentCountryValue = "";
        private String currentEntityKindName = "";
        private String currentEntityKindValue = "";
        private String currentDomainName = "";
        private String currentDomainValue = "";
        private String currentCategoryName = "";
        private String currentCategoryValue = "";
        private String currentSubcategoryName = "";
        private String currentSubcategoryValue = "";
        private String currentSpecificName = "";
        private String currentSpecificValue = "";
        private String currentExtraName = "";
        private String currentExtraValue = "";

        private boolean inCet = false;
        private boolean inEntity = false;
        private int depth = 0;

        public MyHandler() { super(); }

        @Override
        public void startElement(String uri, String localName, String qName, Attributes attributes)
        {
            if (qName.equals("cet"))
            {
                inCet = true;
                return;
            }

            if (!inCet) return;

            if (qName.equals("revision"))
            {
                if (sisoSpecificationTitleDate.isEmpty())
                    sisoSpecificationTitleDate = attributes.getValue("title") + ", " + attributes.getValue("date");
                return;
            }

            if (qName.equals("entity"))
            {
                inEntity = true;
                depth = 0;
                currentCountryName = "";
                currentCountryValue = attributes.getValue("country") != null ? attributes.getValue("country") : "";
                currentEntityKindValue = attributes.getValue("kind") != null ? attributes.getValue("kind") : "";
                currentDomainValue = attributes.getValue("domain") != null ? attributes.getValue("domain") : "";

                // Build a descriptive name from kind+domain
                currentEntityKindName = "Kind" + currentEntityKindValue;
                currentDomainName = "Domain" + currentDomainValue;
                currentCountryName = "Country" + currentCountryValue;
                return;
            }

            if (!inEntity) return;

            // Deprecated entries skipped
            if ("true".equals(attributes.getValue("deprecated")))
                return;

            String description = attributes.getValue("description");
            if (description == null) description = "";
            description = description.trim();

            switch (qName)
            {
                case "category":
                    currentCategoryName = GenerateEnumerations.fixName(description);
                    currentCategoryValue = attributes.getValue("value");
                    if (currentCategoryValue == null) currentCategoryValue = "0";
                    depth = 1;
                    break;

                case "subcategory":
                    currentSubcategoryName = GenerateEnumerations.fixName(description);
                    currentSubcategoryValue = attributes.getValue("value");
                    if (currentSubcategoryValue == null) currentSubcategoryValue = "0";
                    depth = 2;
                    writeEntityTypeClass(description, attributes.getValue("uid"));
                    break;

                case "specific":
                    currentSpecificName = GenerateEnumerations.fixName(description);
                    currentSpecificValue = attributes.getValue("value");
                    if (currentSpecificValue == null) currentSpecificValue = "0";
                    depth = 3;
                    writeEntityTypeClass(description, attributes.getValue("uid"));
                    break;

                case "extra":
                    currentExtraName = GenerateEnumerations.fixName(description);
                    currentExtraValue = attributes.getValue("value");
                    if (currentExtraValue == null) currentExtraValue = "0";
                    depth = 4;
                    writeEntityTypeClass(description, attributes.getValue("uid"));
                    break;
            }
        }

        @Override
        public void endElement(String uri, String localName, String qName)
        {
            switch (qName)
            {
                case "cet":
                    inCet = false;
                    break;
                case "entity":
                    inEntity = false;
                    break;
                case "category":
                    currentCategoryName = "";
                    currentCategoryValue = "";
                    depth = 0;
                    break;
                case "subcategory":
                    currentSubcategoryName = "";
                    currentSubcategoryValue = "";
                    depth = 1;
                    break;
                case "specific":
                    currentSpecificName = "";
                    currentSpecificValue = "";
                    depth = 2;
                    break;
                case "extra":
                    currentExtraName = "";
                    currentExtraValue = "";
                    depth = 3;
                    break;
            }
        }

        private void writeEntityTypeClass(String description, String uid)
        {
            String className = GenerateEnumerations.fixName(description);
            // Remove characters invalid in Python identifiers and filenames
            if (className != null)
                className = className.replaceAll("[^a-zA-Z0-9_]", "");
            if (className == null || className.isEmpty())
                className = "Entity_" + (uid != null ? uid : String.valueOf(entityClassCount));
            // Python class names cannot start with a digit
            if (Character.isDigit(className.charAt(0)))
                className = "_" + className;

            // Build directory path: entities/<country>/<domain>/<category>/
            String subdirPath = currentCountryName + "/" + currentDomainName;
            if (!currentCategoryName.isEmpty())
                subdirPath += "/" + currentCategoryName;

            File subdir = new File(outputDirectory, subdirPath);
            subdir.mkdirs();

            // Build field assignments (default to 0 if empty)
            String kindVal = (currentEntityKindValue != null && !currentEntityKindValue.isEmpty()) ? currentEntityKindValue : "0";
            String domainVal = (currentDomainValue != null && !currentDomainValue.isEmpty()) ? currentDomainValue : "0";
            String countryVal = (currentCountryValue != null && !currentCountryValue.isEmpty()) ? currentCountryValue : "0";
            String catVal = (currentCategoryValue != null && !currentCategoryValue.isEmpty()) ? currentCategoryValue : "0";

            StringBuilder fields = new StringBuilder();
            fields.append("        self.entityKind = ").append(kindVal).append("\n");
            fields.append("        self.domain = ").append(domainVal).append("\n");
            fields.append("        self.country = ").append(countryVal).append("\n");
            fields.append("        self.category = ").append(catVal).append("\n");

            if (depth >= 2 && !currentSubcategoryValue.isEmpty())
                fields.append("        self.subcategory = ").append(currentSubcategoryValue).append("\n");
            if (depth >= 3 && !currentSpecificValue.isEmpty())
                fields.append("        self.specific = ").append(currentSpecificValue).append("\n");
            if (depth >= 4 && !currentExtraValue.isEmpty())
                fields.append("        self.extra = ").append(currentExtraValue).append("\n");

            String docstring = description.replaceAll("\"", "'").replaceAll("\n", " ").replaceAll("\r", " ");

            StringBuilder sb = new StringBuilder();
            sb.append("#\n");
            sb.append("# Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS).\n");
            sb.append("# All rights reserved.\n");
            sb.append("# This work is provided under a BSD open-source license, see project\n");
            sb.append("# license.html and license.txt\n");
            sb.append("#\n\n");
            sb.append("from __future__ import annotations\n");
            sb.append("from opendis7.pdus.EntityType import EntityType\n\n\n");
            sb.append("class ").append(className).append("(EntityType):\n");
            sb.append("    \"\"\"").append(docstring);
            if (uid != null)
                sb.append(" UID ").append(uid);
            sb.append("\"\"\"").append("\n\n");
            sb.append("    def __init__(self):\n");
            sb.append("        super().__init__()\n");
            sb.append(fields);

            File targetFile = new File(subdir, className + ".py");
            try
            {
                targetFile.createNewFile();
                FileWriter fw = new FileWriter(targetFile, StandardCharsets.UTF_8);
                fw.write(sb.toString());
                fw.flush();
                fw.close();
                entityClassCount++;
            }
            catch (IOException ex)
            {
                System.err.println("Error writing " + targetFile.getAbsolutePath() + ": " + ex.getMessage());
            }

            // Write __init__.py in subdir if not exists
            File subdirInit = new File(subdir, "__init__.py");
            if (!subdirInit.exists())
            {
                try
                {
                    subdirInit.createNewFile();
                    FileWriter fw = new FileWriter(subdirInit, StandardCharsets.UTF_8);
                    fw.write("# Auto-generated __init__.py\n");
                    fw.flush();
                    fw.close();
                }
                catch (IOException ex)
                {
                    System.err.println("Error writing " + subdirInit.getAbsolutePath());
                }
            }
        }
    } // end MyHandler
}
