/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD open-source license, see project license.html and license.txt
 */
package edu.nps.moves.dis7.source.generator.entityTypes;

import edu.nps.moves.dis7.source.generator.enumerations.GenerateEnumerations;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.Attributes;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

/**
 * PythonJammerGenerator creates Python jammer technique source code
 * from SISO enumeration definitions. Each jammer technique becomes a Python
 * class with kind, category, subcategory, and specific fields.
 * Parallels GenerateJammers.java but produces Python output.
 *
 * @see GenerateJammers
 * @author DMcG (autogenerated pattern)
 */
public class PythonJammerGenerator
{
    private File outputDirectory;
    private static String outputDirectoryPath = "src-generated/python/opendis7/jammers";
    private static String sisoXmlFile = "xml/SISO/SISO-REF-010.xml";
    private static String sisoSpecificationTitleDate = "";

    private int jammerClassCount = 0;

    /**
     * Constructor
     * @param xmlFile input SISO XML file
     * @param outputDir output directory path
     */
    public PythonJammerGenerator(String xmlFile, String outputDir)
    {
        System.out.println(PythonJammerGenerator.class.getName());
        if (!xmlFile.isEmpty())
            sisoXmlFile = xmlFile;
        if (!outputDir.isEmpty())
            outputDirectoryPath = outputDir;
        System.out.println("          xmlFile=" + sisoXmlFile);
        System.out.println("  outputDirectory=" + outputDirectoryPath);

        outputDirectory = new File(outputDirectoryPath);
        outputDirectory.mkdirs();
        System.out.println("actual directory path=" + outputDirectory.getAbsolutePath());
    }

    /**
     * Main entry point
     * @param args xmlFile, outputDir
     */
    public static void main(String[] args)
    {
        if (args.length >= 2)
        {
            sisoXmlFile = args[0];
            outputDirectoryPath = args[1];
        }
        PythonJammerGenerator generator = new PythonJammerGenerator(sisoXmlFile, outputDirectoryPath);
        try
        {
            generator.run();
        }
        catch (Exception e)
        {
            System.err.println("Error generating Python jammers: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }

    private void run() throws SAXException, IOException, ParserConfigurationException
    {
        File xmlFile = new File(sisoXmlFile);
        SAXParserFactory factory = SAXParserFactory.newInstance();
        factory.setValidating(false);
        factory.setNamespaceAware(true);
        factory.setXIncludeAware(true);

        System.out.println("Begin Python jammer generation...");
        MyHandler handler = new MyHandler();
        factory.newSAXParser().parse(xmlFile, handler);

        writeInitPy();

        System.out.println(PythonJammerGenerator.class.getName() + " complete, " +
            jammerClassCount + " Python jammer classes created.");
    }

    private void writeInitPy() throws IOException
    {
        File initFile = new File(outputDirectory, "__init__.py");
        initFile.createNewFile();
        FileWriter fw = new FileWriter(initFile, StandardCharsets.UTF_8);
        fw.write("#\n");
        fw.write("# Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS).\n");
        fw.write("# All rights reserved.\n");
        fw.write("# Auto-generated __init__.py for opendis7.jammers package\n");
        fw.write("#\n\n");
        fw.write("# Jammer technique classes are organized in subdirectories.\n");
        fw.write("# Import specific jammer types as needed.\n");
        fw.write("\n");
        fw.flush();
        fw.close();
    }

    // ========== SAX Handler ==========

    public class MyHandler extends DefaultHandler
    {
        private boolean inJammerTechnique = false;
        private String currentKindName = "";
        private String currentKindValue = "";
        private String currentCategoryName = "";
        private String currentCategoryValue = "";
        private String currentSubcategoryName = "";
        private String currentSubcategoryValue = "";

        public MyHandler() { super(); }

        @Override
        public void startElement(String uri, String localName, String qName, Attributes attributes)
        {
            if (qName.equals("jammer_technique"))
            {
                inJammerTechnique = true;
                return;
            }
            if (!inJammerTechnique) return;

            if ("true".equals(attributes.getValue("deprecated")))
                return;

            String description = attributes.getValue("description");
            if (description == null) description = "";
            description = description.trim();

            switch (qName)
            {
                case "revision":
                    if (sisoSpecificationTitleDate.isEmpty())
                        sisoSpecificationTitleDate = attributes.getValue("title") + ", " + attributes.getValue("date");
                    break;

                case "jammer_kind":
                    currentKindName = GenerateEnumerations.fixName(description);
                    currentKindValue = attributes.getValue("value");
                    if (currentKindValue == null) currentKindValue = "0";
                    break;

                case "jammer_category":
                    currentCategoryName = GenerateEnumerations.fixName(description);
                    currentCategoryValue = attributes.getValue("value");
                    if (currentCategoryValue == null) currentCategoryValue = "0";
                    break;

                case "jammer_subcategory":
                    currentSubcategoryName = GenerateEnumerations.fixName(description);
                    currentSubcategoryValue = attributes.getValue("value");
                    if (currentSubcategoryValue == null) currentSubcategoryValue = "0";
                    break;

                case "jammer_specific":
                    writeJammerClass(description, attributes.getValue("value"), attributes.getValue("uid"));
                    break;
            }
        }

        @Override
        public void endElement(String uri, String localName, String qName)
        {
            switch (qName)
            {
                case "jammer_technique":
                    inJammerTechnique = false;
                    break;
                case "jammer_kind":
                    currentKindName = "";
                    currentKindValue = "";
                    break;
                case "jammer_category":
                    currentCategoryName = "";
                    currentCategoryValue = "";
                    break;
                case "jammer_subcategory":
                    currentSubcategoryName = "";
                    currentSubcategoryValue = "";
                    break;
            }
        }

        private void writeJammerClass(String description, String specificValue, String uid)
        {
            String className = GenerateEnumerations.fixName(description);
            if (className == null || className.isEmpty())
                className = "Jammer_" + (uid != null ? uid : String.valueOf(jammerClassCount));

            if (specificValue == null) specificValue = "0";

            String subdirPath = currentKindName;
            if (!currentCategoryName.isEmpty())
                subdirPath += "/" + currentCategoryName;

            File subdir = new File(outputDirectory, subdirPath);
            subdir.mkdirs();

            String docstring = description.replaceAll("\"", "'");

            StringBuilder sb = new StringBuilder();
            sb.append("#\n");
            sb.append("# Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS).\n");
            sb.append("# All rights reserved.\n");
            sb.append("# This work is provided under a BSD open-source license, see project\n");
            sb.append("# license.html and license.txt\n");
            sb.append("#\n\n");
            sb.append("from __future__ import annotations\n");
            sb.append("from opendis7.pdus.JammingTechnique import JammingTechnique\n\n\n");
            sb.append("class ").append(className).append("(JammingTechnique):\n");
            sb.append("    \"\"\"").append(docstring);
            if (uid != null)
                sb.append(" UID ").append(uid);
            sb.append("\"\"\"").append("\n\n");
            sb.append("    def __init__(self):\n");
            sb.append("        super().__init__()\n");
            sb.append("        self.kind = ").append(currentKindValue).append("\n");
            sb.append("        self.category = ").append(currentCategoryValue).append("\n");
            sb.append("        self.subcategory = ").append(currentSubcategoryValue).append("\n");
            sb.append("        self.specific = ").append(specificValue).append("\n");

            File targetFile = new File(subdir, className + ".py");
            try
            {
                targetFile.createNewFile();
                FileWriter fw = new FileWriter(targetFile, StandardCharsets.UTF_8);
                fw.write(sb.toString());
                fw.flush();
                fw.close();
                jammerClassCount++;
            }
            catch (IOException ex)
            {
                System.err.println("Error writing " + targetFile.getAbsolutePath() + ": " + ex.getMessage());
            }

            File subdirInit = new File(subdir, "__init__.py");
            if (!subdirInit.exists())
            {
                try
                {
                    subdirInit.createNewFile();
                    FileWriter fw = new FileWriter(subdirInit, StandardCharsets.UTF_8);
                    fw.write("# Auto-generated __init__.py\n");
                    fw.flush();
                    fw.close();
                }
                catch (IOException ex)
                {
                    System.err.println("Error writing " + subdirInit.getAbsolutePath());
                }
            }
        }
    } // end MyHandler
}
