/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD open-source license, see project license.html and license.txt
 */
package edu.nps.moves.dis7.source.generator.enumerations;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.Attributes;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

/**
 * PythonEnumerationGenerator creates Python IntEnum and IntFlag source code
 * from SISO enumeration definitions (SISO-REF-010 XML).
 * Parallels GenerateEnumerations.java but produces Python output.
 * Each enumeration is written to its own .py file.
 *
 * @author DMcG (autogenerated pattern)
 * @see GenerateEnumerations
 */
public class PythonEnumerationGenerator
{
    private File outputDirectory;
    private static String outputDirectoryPath = "src-generated/python/opendis7/enumerations";
    private static String sisoXmlFile = "xml/SISO/SISO-REF-010.xml";

    private Properties uid2ClassName;
    private Properties uid4aliases;
    private Map<String, String> uidClassNames;

    private static String sisoSpecificationTitleDate = "";

    private int enumClassCount = 0;
    private List<String> generatedClassNames = new ArrayList<>();

    /**
     * Constructor
     * @param xmlFile input SISO XML file
     * @param outputDir output directory path
     */
    public PythonEnumerationGenerator(String xmlFile, String outputDir)
    {
        System.out.println(PythonEnumerationGenerator.class.getName());
        if (!xmlFile.isEmpty())
            sisoXmlFile = xmlFile;
        if (!outputDir.isEmpty())
            outputDirectoryPath = outputDir;
        System.out.println("          xmlFile=" + sisoXmlFile);
        System.out.println("  outputDirectory=" + outputDirectoryPath);

        outputDirectory = new File(outputDirectoryPath);
        outputDirectory.mkdirs();
        System.out.println("actual directory path=" + outputDirectory.getAbsolutePath());
    }

    /**
     * Main entry point
     * @param args xmlFile, outputDir
     */
    public static void main(String[] args)
    {
        if (args.length >= 2)
        {
            sisoXmlFile = args[0];
            outputDirectoryPath = args[1];
        }
        PythonEnumerationGenerator generator = new PythonEnumerationGenerator(sisoXmlFile, outputDirectoryPath);
        try
        {
            generator.run();
        }
        catch (Exception e)
        {
            System.err.println("Error generating Python enumerations: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }

    private void run() throws SAXException, IOException, ParserConfigurationException
    {
        uid2ClassName = new Properties();
        uid2ClassName.load(GenerateEnumerations.class.getResourceAsStream("Uid2ClassName.properties"));
        uid4aliases = new Properties();
        uid4aliases.load(GenerateEnumerations.class.getResourceAsStream("uid4aliases.properties"));

        uidClassNames = new HashMap<>();

        File xmlFile = new File(sisoXmlFile);
        SAXParserFactory factory = SAXParserFactory.newInstance();
        factory.setValidating(false);
        factory.setNamespaceAware(true);
        factory.setXIncludeAware(true);

        System.out.println("Begin uid preprocess for Python enumerations...");
        factory.newSAXParser().parse(xmlFile, new UidCollector());

        System.out.println("Begin Python enumeration generation...");
        MyHandler handler = new MyHandler();
        factory.newSAXParser().parse(xmlFile, handler);

        // Write __init__.py
        writeInitPy();

        System.out.println(PythonEnumerationGenerator.class.getName() + " complete, " +
            enumClassCount + " Python enum classes created.");
    }

    private void writeInitPy() throws IOException
    {
        File initFile = new File(outputDirectory, "__init__.py");
        initFile.createNewFile();
        FileWriter fw = new FileWriter(initFile, StandardCharsets.UTF_8);
        fw.write("#\n");
        fw.write("# Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS).\n");
        fw.write("# All rights reserved.\n");
        fw.write("# Auto-generated __init__.py for opendis7.enumerations package\n");
        fw.write("#\n\n");

        for (String className : generatedClassNames)
        {
            fw.write("from opendis7.enumerations." + className + " import " + className + "\n");
        }
        fw.write("\n");
        fw.flush();
        fw.close();
        System.out.println("Created enumerations __init__.py with " + generatedClassNames.size() + " imports");
    }

    // ========== Inner data classes ==========

    class EnumElem
    {
        String uid;
        String name;
        String size;
        List<EnumRowElem> elems = new ArrayList<>();
    }

    class EnumRowElem
    {
        String value;
        String description;
    }

    class BitfieldElem
    {
        String name;
        String size;
        String uid;
        List<BitfieldRowElem> elems = new ArrayList<>();
    }

    class BitfieldRowElem
    {
        String name;
        String bitposition;
        String length = "1";
        String description;
    }

    class DictionaryElem
    {
        String name;
        String uid;
        List<DictionaryRowElem> elems = new ArrayList<>();
    }

    class DictionaryRowElem
    {
        String value;
        String description;
    }

    // ========== UID Collector ==========

    public class UidCollector extends DefaultHandler
    {
        public UidCollector() { super(); }

        @Override
        public void startElement(String uri, String localName, String qName, Attributes attributes)
        {
            switch (qName)
            {
                case "enum":
                case "bitfield":
                case "dict":
                    String uid = attributes.getValue("uid");
                    if (uid != null)
                    {
                        String name = GenerateEnumerations.fixName(attributes.getValue("name"));
                        String name2 = PythonEnumerationGenerator.this.uid2ClassName.getProperty(uid);
                        if (name2 != null)
                            uidClassNames.put(uid, name2);
                        else
                            uidClassNames.put(uid, name);
                    }
                default:
            }
        }
    }

    // ========== SAX Handler ==========

    public class MyHandler extends DefaultHandler
    {
        public MyHandler() { super(); }

        List<EnumElem> enums = new ArrayList<>();
        EnumElem currentEnum;
        EnumRowElem currentEnumRow;

        List<BitfieldElem> bitfields = new ArrayList<>();
        BitfieldElem currentBitfield;
        BitfieldRowElem currentBitfieldRow;

        List<DictionaryElem> dictionaries = new ArrayList<>();
        DictionaryElem currentDict;
        DictionaryRowElem currentDictRow;

        @Override
        public void startElement(String uri, String localName, String qName, Attributes attributes)
        {
            if (qName.equals("category") && "true".equals(attributes.getValue("deprecated")))
                return;

            switch (qName)
            {
                case "enum":
                    currentEnum = new EnumElem();
                    currentEnum.name = GenerateEnumerations.fixName(attributes.getValue("name"));
                    currentEnum.uid = attributes.getValue("uid");
                    currentEnum.size = attributes.getValue("size");
                    enums.add(currentEnum);
                    break;

                case "enumrow":
                    if (currentEnum == null) break;
                    currentEnumRow = new EnumRowElem();
                    currentEnumRow.description = attributes.getValue("description");
                    if (currentEnumRow.description != null)
                        currentEnumRow.description = normalizeDescription(currentEnumRow.description);
                    currentEnumRow.value = attributes.getValue("value");
                    if (currentEnumRow.value == null) currentEnumRow.value = "0";
                    // Strip leading zeros (Python 3 disallows 0010, 0100, etc.)
                    currentEnumRow.value = stripLeadingZeros(currentEnumRow.value);
                    // Special case: value exceeding max int
                    if (currentEnumRow.value.equals("2147483648"))
                        currentEnumRow.value = "2147483647";
                    // Ensure value is a valid integer
                    if (!isValidIntLiteral(currentEnumRow.value))
                        currentEnumRow.value = "0";
                    currentEnum.elems.add(currentEnumRow);
                    break;

                case "meta":
                    if (currentEnum == null || currentEnumRow == null) break;
                    if ((currentEnumRow.description == null) || currentEnumRow.description.isEmpty())
                    {
                        String key = attributes.getValue("key");
                        String value = attributes.getValue("value");
                        if (key != null)
                            currentEnumRow.description = key.toUpperCase() + "_";
                        if (value != null)
                            currentEnumRow.description += value;
                        if (currentEnumRow.description != null)
                            currentEnumRow.description = normalizeDescription(currentEnumRow.description);
                    }
                    break;

                case "bitfield":
                    currentBitfield = new BitfieldElem();
                    currentBitfield.name = GenerateEnumerations.fixName(attributes.getValue("name"));
                    currentBitfield.size = attributes.getValue("size");
                    currentBitfield.uid = attributes.getValue("uid");
                    bitfields.add(currentBitfield);
                    break;

                case "bitfieldrow":
                    if (currentBitfield == null) break;
                    currentBitfieldRow = new BitfieldRowElem();
                    currentBitfieldRow.name = GenerateEnumerations.fixName(attributes.getValue("name"));
                    currentBitfieldRow.description = attributes.getValue("description");
                    if (currentBitfieldRow.description != null)
                        currentBitfieldRow.description = normalizeDescription(currentBitfieldRow.description);
                    currentBitfieldRow.bitposition = attributes.getValue("bit_position");
                    String len = attributes.getValue("length");
                    if (len != null)
                        currentBitfieldRow.length = len;
                    currentBitfield.elems.add(currentBitfieldRow);
                    break;

                case "dict":
                    currentDict = new DictionaryElem();
                    currentDict.name = GenerateEnumerations.fixName(attributes.getValue("name"));
                    currentDict.uid = attributes.getValue("uid");
                    dictionaries.add(currentDict);
                    break;

                case "dictrow":
                    if (currentDict == null) break;
                    currentDictRow = new DictionaryRowElem();
                    currentDictRow.value = attributes.getValue("value");
                    currentDictRow.description = attributes.getValue("description");
                    if (currentDictRow.description != null)
                        currentDictRow.description = normalizeDescription(currentDictRow.description);
                    currentDict.elems.add(currentDictRow);
                    break;

                case "revision":
                    if (sisoSpecificationTitleDate == null || sisoSpecificationTitleDate.isEmpty())
                        sisoSpecificationTitleDate = attributes.getValue("title") + ", " + attributes.getValue("date");
                    break;

                default:
                    break;
            }
        }

        @Override
        public void endElement(String uri, String localName, String qName)
        {
            switch (qName)
            {
                case "enum":
                    if (currentEnum != null)
                        writeOutEnum(currentEnum);
                    currentEnum = null;
                    break;
                case "enumrow":
                    currentEnumRow = null;
                    break;
                case "bitfield":
                    if (currentBitfield != null)
                        writeOutBitfield(currentBitfield);
                    currentBitfield = null;
                    break;
                case "bitfieldrow":
                    currentBitfieldRow = null;
                    break;
                case "dict":
                    if (currentDict != null)
                        writeOutDict(currentDict);
                    currentDict = null;
                    break;
                case "dictrow":
                    currentDictRow = null;
                    break;
            }
        }

        // ========== Writers ==========

        Set<String> enumNames = new HashSet<>();

        private void writeOutEnum(EnumElem el)
        {
            String clsName = uidClassNames.get(el.uid);
            if (clsName == null)
            {
                System.err.println("*** Didn't find class name for uid=" + el.uid + ", skipping");
                return;
            }
            String className = fixClassName(clsName);

            StringBuilder sb = new StringBuilder();
            sb.append("#\n");
            sb.append("# Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS).\n");
            sb.append("# All rights reserved.\n");
            sb.append("# This work is provided under a BSD open-source license, see project\n");
            sb.append("# license.html and license.txt\n");
            sb.append("#\n\n");
            sb.append("from __future__ import annotations\n");
            sb.append("from enum import IntEnum\n\n\n");
            sb.append("class ").append(className).append("(IntEnum):\n");
            sb.append("    \"\"\"").append(normalizeDescription(el.name));
            if (sisoSpecificationTitleDate != null && !sisoSpecificationTitleDate.isEmpty())
                sb.append(" - ").append(normalizeDescription(sisoSpecificationTitleDate));
            sb.append(", UID ").append(el.uid).append("\"\"\"").append("\n\n");

            enumNames.clear();
            if (el.elems.isEmpty())
            {
                sb.append("    UNDEFINED = 0  # No values defined in SISO spec\n");
            }
            else
            {
                for (EnumRowElem row : el.elems)
                {
                    String enumName = createPythonEnumName(row.description);
                    if (enumName == null || enumName.isEmpty())
                        enumName = "VALUE_" + row.value;

                    // Ensure unique
                    String originalName = enumName;
                    int dupCount = 1;
                    while (enumNames.contains(enumName))
                    {
                        enumName = originalName + "_" + dupCount;
                        dupCount++;
                    }
                    enumNames.add(enumName);

                    String comment = (row.description != null) ? normalizeDescription(row.description) : "";
                    sb.append("    ").append(enumName).append(" = ").append(row.value);
                    if (!comment.isEmpty())
                        sb.append("  # ").append(comment);
                    sb.append("\n");
                }
            }

            // get_enum_for_value classmethod
            sb.append("\n");
            sb.append("    @classmethod\n");
            sb.append("    def get_enum_for_value(cls, value: int) -> '").append(className).append("':\n");
            sb.append("        \"\"\"Return the enumeration member with the given value, or None if not found.\"\"\"\n");
            sb.append("        try:\n");
            sb.append("            return cls(value)\n");
            sb.append("        except ValueError:\n");
            sb.append("            return None\n");

            writeToFile(className, sb.toString());
            generatedClassNames.add(className);
            enumClassCount++;
        }

        private void writeOutBitfield(BitfieldElem el)
        {
            String clsName = uidClassNames.get(el.uid);
            if (clsName == null)
            {
                System.err.println("*** Didn't find class name for bitfield uid=" + el.uid + ", skipping");
                return;
            }
            String className = fixClassName(clsName);

            StringBuilder sb = new StringBuilder();
            sb.append("#\n");
            sb.append("# Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS).\n");
            sb.append("# All rights reserved.\n");
            sb.append("# This work is provided under a BSD open-source license, see project\n");
            sb.append("# license.html and license.txt\n");
            sb.append("#\n\n");
            sb.append("from __future__ import annotations\n");
            sb.append("from enum import IntFlag\n\n\n");
            sb.append("class ").append(className).append("(IntFlag):\n");
            sb.append("    \"\"\"").append(normalizeDescription(el.name));
            if (sisoSpecificationTitleDate != null && !sisoSpecificationTitleDate.isEmpty())
                sb.append(" - ").append(normalizeDescription(sisoSpecificationTitleDate));
            sb.append(", UID ").append(el.uid).append("\"\"\"").append("\n\n");

            Set<String> bitfieldNames = new HashSet<>();
            if (el.elems.isEmpty())
            {
                sb.append("    UNDEFINED = 0  # No values defined in SISO spec\n");
            }
            else
            {
                for (BitfieldRowElem row : el.elems)
                {
                    String fieldName = createPythonEnumName(row.name);
                    if (fieldName == null || fieldName.isEmpty())
                        fieldName = "BIT_" + row.bitposition;

                    // Ensure unique
                    String originalName = fieldName;
                    int dupCount = 1;
                    while (bitfieldNames.contains(fieldName))
                    {
                        fieldName = originalName + "_" + dupCount;
                        dupCount++;
                    }
                    bitfieldNames.add(fieldName);

                    // Calculate flag value from bit position and length
                    int bitPos = Integer.parseInt(row.bitposition);
                    int bitLen = Integer.parseInt(row.length);
                    long flagValue;
                    if (bitLen == 1)
                    {
                        flagValue = 1L << bitPos;
                    }
                    else
                    {
                        flagValue = ((1L << bitLen) - 1) << bitPos;
                    }

                    String comment = (row.description != null) ? normalizeDescription(row.description) : "";
                    sb.append("    ").append(fieldName).append(" = ").append(flagValue);
                    if (!comment.isEmpty())
                        sb.append("  # ").append(comment);
                    sb.append("\n");
                }
            }

            // get_enum_for_value classmethod
            sb.append("\n");
            sb.append("    @classmethod\n");
            sb.append("    def get_enum_for_value(cls, value: int) -> '").append(className).append("':\n");
            sb.append("        \"\"\"Return the flag member(s) matching the given value.\"\"\"\n");
            sb.append("        try:\n");
            sb.append("            return cls(value)\n");
            sb.append("        except ValueError:\n");
            sb.append("            return None\n");

            writeToFile(className, sb.toString());
            generatedClassNames.add(className);
            enumClassCount++;
        }

        private void writeOutDict(DictionaryElem el)
        {
            String clsName = uidClassNames.get(el.uid);
            if (clsName == null)
            {
                System.err.println("*** Didn't find class name for dict uid=" + el.uid + ", skipping");
                return;
            }
            String className = fixClassName(clsName);

            StringBuilder sb = new StringBuilder();
            sb.append("#\n");
            sb.append("# Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS).\n");
            sb.append("# All rights reserved.\n");
            sb.append("# This work is provided under a BSD open-source license, see project\n");
            sb.append("# license.html and license.txt\n");
            sb.append("#\n\n");
            sb.append("from __future__ import annotations\n");
            sb.append("from enum import IntEnum\n\n\n");
            sb.append("class ").append(className).append("(IntEnum):\n");
            sb.append("    \"\"\"").append(normalizeDescription(el.name));
            if (sisoSpecificationTitleDate != null && !sisoSpecificationTitleDate.isEmpty())
                sb.append(" - ").append(normalizeDescription(sisoSpecificationTitleDate));
            sb.append(", UID ").append(el.uid).append("\"\"\"").append("\n\n");

            Set<String> dictNames = new HashSet<>();
            if (el.elems.isEmpty())
            {
                sb.append("    UNDEFINED = 0  # No values defined in SISO spec\n");
            }
            else
            {
                for (DictionaryRowElem row : el.elems)
                {
                    // For dict entries, value is the key and description is the name
                    String enumName = row.value.replaceAll("[^a-zA-Z0-9_]", "");
                    if (enumName.isEmpty())
                        enumName = "VALUE_" + row.value.replaceAll("[^a-zA-Z0-9_]", "");
                    if (enumName.isEmpty())
                        enumName = "VALUE_0";
                    // Python identifiers cannot start with a digit
                    if (Character.isDigit(enumName.charAt(0)))
                        enumName = "VALUE_" + enumName;

                    // Ensure unique
                    String originalName = enumName;
                    int dupCount = 1;
                    while (dictNames.contains(enumName))
                    {
                        enumName = originalName + "_" + dupCount;
                        dupCount++;
                    }
                    dictNames.add(enumName);

                    String desc = (row.description != null) ? normalizeDescription(row.description) : "";
                    // Dict entries use the string value as the enum value - parse as int
                    String numValue = row.value.replaceAll("[^0-9-]", "");
                    if (numValue.isEmpty() || !isValidIntLiteral(numValue)) numValue = "0";

                    sb.append("    ").append(enumName).append(" = ").append(numValue);
                    if (!desc.isEmpty())
                        sb.append("  # ").append(desc);
                    sb.append("\n");
                }
            }

            // get_enum_for_value classmethod
            sb.append("\n");
            sb.append("    @classmethod\n");
            sb.append("    def get_enum_for_value(cls, value: int) -> '").append(className).append("':\n");
            sb.append("        \"\"\"Return the enumeration member with the given value, or None if not found.\"\"\"\n");
            sb.append("        try:\n");
            sb.append("            return cls(value)\n");
            sb.append("        except ValueError:\n");
            sb.append("            return None\n");

            writeToFile(className, sb.toString());
            generatedClassNames.add(className);
            enumClassCount++;
        }
    } // end MyHandler

    // ========== Utility methods ==========

    private void writeToFile(String className, String content)
    {
        File targetFile = new File(outputDirectory, className + ".py");
        try
        {
            targetFile.getParentFile().mkdirs();
            targetFile.createNewFile();
            FileWriter fw = new FileWriter(targetFile, StandardCharsets.UTF_8);
            fw.write(content);
            fw.flush();
            fw.close();
        }
        catch (IOException ex)
        {
            System.err.println("Error writing " + targetFile.getAbsolutePath() + ": " + ex.getMessage());
            ex.printStackTrace(System.err);
        }
    }

    /**
     * Fix class name for Python - remove problematic characters.
     */
    private String fixClassName(String name)
    {
        String fixed = name;
        if (fixed.contains("Link11/11"))
            fixed = fixed.replace("Link11/11B", "Link11_11B");
        if (fixed.contains("%"))
            fixed = fixed.replaceAll("%", "_PERCENT");
        return fixed;
    }

    /**
     * Create a Python-safe enum member name from a description string.
     * Converts to UPPER_SNAKE_CASE.
     */
    private String createPythonEnumName(String description)
    {
        if (description == null || description.trim().isEmpty())
            return null;

        // Clean up description for use as Python identifier
        String name = description.trim();

        // Replace common separators with spaces first
        name = name.replaceAll("[,/\\-—.&\"'()]", " ");

        // Remove non-alphanumeric except spaces and underscores
        name = name.replaceAll("[^a-zA-Z0-9_ ]", "");

        // Normalize whitespace to single underscores
        name = name.trim().replaceAll("\\s+", "_");

        // Convert to uppercase
        name = name.toUpperCase();

        // Remove leading digits (invalid Python identifier)
        if (!name.isEmpty() && Character.isDigit(name.charAt(0)))
            name = "VALUE_" + name;

        // Remove double underscores
        name = name.replaceAll("__+", "_");

        // Remove trailing underscore
        if (name.endsWith("_"))
            name = name.substring(0, name.length() - 1);

        if (name.isEmpty())
            return null;

        return name;
    }

    /**
     * Normalize description string - remove problematic characters.
     */
    private static String normalizeDescription(String s)
    {
        if (s == null) return null;
        return s.replaceAll("\"", "'").replaceAll("\n", " ").replaceAll("\r", " ").trim();
    }

    /**
     * Strip leading zeros from a numeric string, preserving negative sign and "0" itself.
     * E.g. "0010" -> "10", "0" -> "0", "-0010" -> "-10"
     */
    private static String stripLeadingZeros(String s)
    {
        if (s == null || s.isEmpty()) return "0";
        boolean negative = s.startsWith("-");
        String digits = negative ? s.substring(1) : s;
        digits = digits.replaceFirst("^0+", "");
        if (digits.isEmpty()) digits = "0";
        return negative ? "-" + digits : digits;
    }

    /**
     * Check if a string is a valid Python integer literal.
     */
    private static boolean isValidIntLiteral(String s)
    {
        if (s == null || s.isEmpty()) return false;
        try
        {
            Long.parseLong(s);
            return true;
        }
        catch (NumberFormatException e)
        {
            return false;
        }
    }
}
